spring.application.name=modusweb

spring.datasource.url=jdbc:postgresql://localhost:5432/modusweb
spring.datasource.username=lfernandes
spring.datasource.password=lcklaura001*
spring.jpa.hibernate.ddl-auto=update
# Configuração de upload de arquivo
spring.servlet.multipart.max-file-size=50MB
